In [1]:
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv("../data/Loan_Default.csv")
df.head()

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,EXP,758,CIB,25-34,to_inst,98.728814,south,direct,1,45.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,EQUI,552,EXP,55-64,to_inst,NaN,North,direct,1,NaN
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,EXP,834,CIB,35-44,to_inst,80.019685,south,direct,0,46.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,EXP,587,CIB,45-54,not_inst,69.376900,North,direct,0,42.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,CRIF,602,EXP,25-34,not_inst,91.886544,North,direct,0,39.0

In [3]:
df.columns

Index(['ID', 'year', 'loan_limit', 'Gender', 'approv_in_adv', 'loan_type',
       'loan_purpose', 'Credit_Worthiness', 'open_credit',
       'business_or_commercial', 'loan_amount', 'rate_of_interest',
       'Interest_rate_spread', 'Upfront_charges', 'term', 'Neg_ammortization',
       'interest_only', 'lump_sum_payment', 'property_value',
       'construction_type', 'occupancy_type', 'Secured_by', 'total_units',
       'income', 'credit_type', 'Credit_Score', 'co-applicant_credit_type',
       'age', 'submission_of_application', 'LTV', 'Region', 'Security_Type',
       'Status', 'dtir1'],
      dtype='str')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 148670 entries, 0 to 148669
Data columns (total 34 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   ID                         148670 non-null  int64
 1   year                       148670 non-null  int64
 2   loan_limit                 145326 non-null  str
 3   Gender                     148670 non-null  str
 4   approv_in_adv              147762 non-null  str
 5   loan_type                  148670 non-null  str
 6   loan_purpose               148536 non-null  str
 7   Credit_Worthiness          148670 non-null  str
 8   open_credit                148670 non-null  str
 9   business_or_commercial     148670 non-null  str
 10  loan_amount                148670 non-null  int64
 11  rate_of_interest           112231 non-null  float64
 12  Interest_rate_spread       112031 non-null  float64
 13  Upfront_charges            109028 non-null  float64
 14  term                       148629 non-null  float64
 15  Neg_ammortization          148549 non-null  str
 16  interest_only              148670 non-null  str
 17  lump_sum_payment           148670 non-null  str
 18  property_value             133572 non-null  float64
 19  construction_type          148670 non-null  str
 20  occupancy_type             148670 non-null  str
 21  Secured_by                 148670 non-null  str
 22  total_units                148670 non-null  str
 23  income                     139520 non-null  float64
 24  credit_type                148670 non-null  str
 25  Credit_Score               148670 non-null  int64
 26  co-applicant_credit_type   148670 non-null  str
 27  age                        148470 non-null  str
 28  submission_of_application  148470 non-null  str
 29  LTV                        133572 non-null  float64
 30  Region                     148670 non-null  str
 31  Security_Type              148670 non-null  str
 32  Status                     148670 non-null  int64
 33  dtir1                      124549 non-null  float64
dtypes: float64(8), int64(5), str(21)
memory usage: 38.6 MB

In [5]:
df.describe()

,ID,year,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,property_value,income,Credit_Score,LTV,Status,dtir1
count,148670.000000,148670.0,1.486700e+05,112231.000000,112031.000000,109028.000000,148629.000000,1.335720e+05,139520.000000,148670.000000,133572.000000,148670.000000,124549.000000
mean,99224.500000,2019.0,3.311177e+05,4.045476,0.441656,3224.996127,335.136582,4.978935e+05,6957.338876,699.789103,72.746457,0.246445,37.732932
std,42917.476598,0.0,1.839093e+05,0.561391,0.513043,3251.121510,58.409084,3.599353e+05,6496.586382,115.875857,39.967603,0.430942,10.545435
min,24890.000000,2019.0,1.650000e+04,0.000000,-3.638000,0.000000,96.000000,8.000000e+03,0.000000,500.000000,0.967478,0.000000,5.000000
25%,62057.250000,2019.0,1.965000e+05,3.625000,0.076000,581.490000,360.000000,2.680000e+05,3720.000000,599.000000,60.474860,0.000000,31.000000
50%,99224.500000,2019.0,2.965000e+05,3.990000,0.390400,2596.450000,360.000000,4.180000e+05,5760.000000,699.000000,75.135870,0.000000,39.000000
75%,136391.750000,2019.0,4.365000e+05,4.375000,0.775400,4812.500000,360.000000,6.280000e+05,8520.000000,800.000000,86.184211,0.000000,45.000000
max,173559.000000,2019.0,3.576500e+06,8.000000,3.357000,60000.000000,360.000000,1.650800e+07,578580.000000,900.000000,7831.250000,1.000000,61.000000

In [6]:
df.isnull().sum()

ID                               0
year                             0
loan_limit                    3344
Gender                           0
approv_in_adv                  908
loan_type                        0
loan_purpose                   134
Credit_Worthiness                0
open_credit                      0
business_or_commercial           0
loan_amount                      0
rate_of_interest             36439
Interest_rate_spread         36639
Upfront_charges              39642
term                            41
Neg_ammortization              121
interest_only                    0
lump_sum_payment                 0
property_value               15098
construction_type                0
occupancy_type                   0
Secured_by                       0
total_units                      0
income                        9150
credit_type                      0
Credit_Score                     0
co-applicant_credit_type         0
age                            200
submission_of_application      200
LTV                          15098
Region                           0
Security_Type                    0
Status                           0
dtir1                        24121
dtype: int64

In [7]:
df["Status"].value_counts()
df["Status"].value_counts(normalize=True) * 100

Status
0    75.355485
1    24.644515
Name: proportion, dtype: float64

In [8]:
df.dtypes.value_counts()

str        21
float64     8
int64       5
Name: count, dtype: int64

In [9]:
fig = px.bar(
    df["Status"].value_counts(),
    title="Target Distribution"
)

In [10]:
fig.show()

In [11]:
missing = df.isnull().sum().sort_values(ascending=False)

missing[missing > 0]

Upfront_charges              39642
Interest_rate_spread         36639
rate_of_interest             36439
dtir1                        24121
property_value               15098
LTV                          15098
income                        9150
loan_limit                    3344
approv_in_adv                  908
age                            200
submission_of_application      200
loan_purpose                   134
Neg_ammortization              121
term                            41
dtype: int64

In [12]:
missing_pct = (df.isnull().sum() / len(df)) * 100
missing_pct.sort_values(ascending=False)

Upfront_charges              26.664425
Interest_rate_spread         24.644515
rate_of_interest             24.509989
dtir1                        16.224524
property_value               10.155378
LTV                          10.155378
income                        6.154571
loan_limit                    2.249277
approv_in_adv                 0.610749
age                           0.134526
submission_of_application     0.134526
loan_purpose                  0.090133
Neg_ammortization             0.081388
term                          0.027578
year                          0.000000
ID                            0.000000
business_or_commercial        0.000000
open_credit                   0.000000
lump_sum_payment              0.000000
interest_only                 0.000000
loan_amount                   0.000000
Gender                        0.000000
loan_type                     0.000000
Credit_Worthiness             0.000000
occupancy_type                0.000000
construction_type             0.000000
Credit_Score                  0.000000
credit_type                   0.000000
total_units                   0.000000
Secured_by                    0.000000
co-applicant_credit_type      0.000000
Region                        0.000000
Security_Type                 0.000000
Status                        0.000000
dtype: float64

In [13]:
loan_amountfig = px.histogram(df, x="loan_amount", color="Status", marginal="box")
fig.show()

In [14]:
px.histogram(df, x="income", color="Status")

In [15]:
num_cols = df.select_dtypes(include=["int64", "float64"]).columns

In [16]:
df[num_cols].corrwith(df["Status"]).sort_values()

/mnt/d/ML-Projects/loan-default/.venv/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3023: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/mnt/d/ML-Projects/loan-default/.venv/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3024: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

income                 -0.065119
property_value         -0.048864
loan_amount            -0.036825
Upfront_charges        -0.019138
term                   -0.000240
ID                      0.001703
Credit_Score            0.004004
rate_of_interest        0.022957
LTV                     0.038895
dtir1                   0.078083
Status                  1.000000
year                         NaN
Interest_rate_spread         NaN
dtype: float64

In [17]:
df.groupby("loan_purpose")["Status"].mean().sort_values()

loan_purpose
p4    0.229749
p3    0.250223
p1    0.258768
p2    0.330788
Name: Status, dtype: float64

In [18]:
cat_cols = df.select_dtypes(include=["object"]).columns

/tmp/ipykernel_4758/1929174544.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=["object"]).columns

In [19]:
for col in cat_cols:
    print("\n", col)
    print(df.groupby(col)["Status"].mean().sort_values())

 loan_limit
loan_limit
cf     0.239708
ncf    0.332131
Name: Status, dtype: float64

 Gender
Gender
Joint                0.191623
Female               0.251155
Male                 0.261914
Sex Not Available    0.285908
Name: Status, dtype: float64

 approv_in_adv
approv_in_adv
pre      0.208937
nopre    0.253272
Name: Status, dtype: float64

 loan_type
loan_type
type1    0.227749
type3    0.250560
type2    0.345439
Name: Status, dtype: float64

 loan_purpose
loan_purpose
p4    0.229749
p3    0.250223
p1    0.258768
p2    0.330788
Name: Status, dtype: float64

 Credit_Worthiness
Credit_Worthiness
l1    0.243277
l2    0.317736
Name: Status, dtype: float64

 open_credit
open_credit
opc     0.176259
nopc    0.246709
Name: Status, dtype: float64

 business_or_commercial
business_or_commercial
nob/c    0.230377
b/c      0.345439
Name: Status, dtype: float64

 Neg_ammortization
Neg_ammortization
not_neg    0.223805
neg_amm    0.445965
Name: Status, dtype: float64

 interest_only
interest_only
not_int     0.245105
int_only    0.273136
Name: Status, dtype: float64

 lump_sum_payment
lump_sum_payment
not_lpsm    0.234097
lpsm        0.776596
Name: Status, dtype: float64

 construction_type
construction_type
sb    0.246278
mh    1.000000
Name: Status, dtype: float64

 occupancy_type
occupancy_type
pr    0.243045
sr    0.271333
ir    0.299864
Name: Status, dtype: float64

 Secured_by
Secured_by
home    0.246278
land    1.000000
Name: Status, dtype: float64

 total_units
total_units
1U    0.244969
4U    0.296875
2U    0.345295
3U    0.384224
Name: Status, dtype: float64

 credit_type
credit_type
CIB     0.158041
EXP     0.159854
CRIF    0.162343
EQUI    0.999935
Name: Status, dtype: float64

 co-applicant_credit_type
co-applicant_credit_type
CIB    0.184334
EXP    0.308651
Name: Status, dtype: float64

 age
age
25-34    0.221920
35-44    0.222713
45-54    0.240467
55-64    0.258868
65-74    0.268560
<25      0.289454
>74      0.300070
Name: Status, dtype: float64

 submission_of_application
submission_of_application
not_inst    0.175213
to_inst     0.284019
Name: Status, dtype: float64

 Region
Region
North         0.225114
south         0.266293
central       0.275382
North-East    0.304453
Name: Status, dtype: float64

 Security_Type
Security_Type
direct      0.246278
Indriect    1.000000
Name: Status, dtype: float64

In [20]:
df["credit_type"].value_counts()

credit_type
CIB     48152
CRIF    43901
EXP     41319
EQUI    15298
Name: count, dtype: int64

In [21]:
pd.crosstab(df["credit_type"], df["Status"])

Status           0      1
credit_type
CIB          40542   7610
CRIF         36774   7127
EQUI             1  15297
EXP          34714   6605

In [22]:
pd.crosstab(df["Security_Type"], df["Status"])

Status              0      1
Security_Type
Indriect            0     33
direct         112031  36606

In [23]:
pd.crosstab(df["construction_type"], df["Status"])

Status                  0      1
construction_type
mh                      0     33
sb                 112031  36606

In [24]:
pd.crosstab(df["Secured_by"], df["Status"])

Status           0      1
Secured_by
home        112031  36606
land             0     33